[phases.setup]
nixPkgs = ["jdk17"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests -q"]

[start]
cmd = "java -Xms64m -Xmx384m -XX:MaxMetaspaceSize=128m -XX:+UseG1GC -jar target/contab360-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"
